//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilot.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pilot.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddShortcutFormPage {
            get {
                return ResourceManager.GetString("AddShortcutFormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstecz.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz.
        /// </summary>
        public static string ConnectConfigPage {
            get {
                return ResourceManager.GetString("ConnectConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozłącz.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string EditShortcutsPage {
            get {
                return ResourceManager.GetString("EditShortcutsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres IP komputera:.
        /// </summary>
        public static string IPAddressConfigPage {
            get {
                return ResourceManager.GetString("IPAddressConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klawiatura.
        /// </summary>
        public static string KeyboardMainPage {
            get {
                return ResourceManager.GetString("KeyboardMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        public static string NameShortcutFormPage {
            get {
                return ResourceManager.GetString("NameShortcutFormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z komputerem.
        /// </summary>
        public static string NoConnectionError {
            get {
                return ResourceManager.GetString("NoConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string PasswordConfigPage {
            get {
                return ResourceManager.GetString("PasswordConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola odtwarzania:.
        /// </summary>
        public static string PlaybackControlShortcutsPage {
            get {
                return ResourceManager.GetString("PlaybackControlShortcutsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PortConfigPage {
            get {
                return ResourceManager.GetString("PortConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string SearchConfigPage {
            get {
                return ResourceManager.GetString("SearchConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista serwerów:.
        /// </summary>
        public static string ServersListSearchPage {
            get {
                return ResourceManager.GetString("ServersListSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skróty.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.example.com lub example.com.
        /// </summary>
        public static string URLExampleShortcutFormPage {
            get {
                return ResourceManager.GetString("URLExampleShortcutFormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres WWW:.
        /// </summary>
        public static string URLShortcutFormPage {
            get {
                return ResourceManager.GetString("URLShortcutFormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy numer portu.
        /// </summary>
        public static string WrongPortNumberError {
            get {
                return ResourceManager.GetString("WrongPortNumberError", resourceCulture);
            }
        }
    }
}
